env: "local" # local, dev, prod
http_server:
  host: "localhost"
  port: 8080
  timeout: 5s
  idle_timeout: 60s
clients:
  auth_service:
    host: "localhost"
    port: 50051
    timeout: 5s
    retries_count: 3
    insecure: false
app_secret: "secret"